version: '3'

services:
  marplacode-web:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules
    ports:
      - 1234:1234
    command: npm start