version: '3'

services:
  marplacode-web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    environment:
      - PORT=80
    ports:
      - "8080:80"
    entrypoint:
     - npm
     - start
  not-gamp-machine-api:
    build: ../not-gamp-machine-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=8586
    ports:
      - "8081:8586"
    entrypoint:
     - npm
     - start
    networks:
     - notGampApi
  not-gamp-machine-ui:
    build: ../not-gamp-machine-ui
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    environment:
      - PORT=8687
    ports:
      - "8082:8687"
    entrypoint:
     - npm
     - start
    networks:
     - notGampApi

networks:
 notGampApi:
