version: '3'

services:
  marplacode-web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 8080:1234
    command: npm start
  not-gamp-machine-api:
    build: ../not-gamp-machine-api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 8081:1234
    command: npm start
  not-gamp-machine-ui:
    build: ../not-gamp-machine-ui
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    links:
      - not-gamp-machine-api
    ports:
      - 8082:1234
    command: npm start